// 001 HQ — Salary accrual (Form 02) and payment (Form 03) of head-office / production units.
import type { EmployeeColumn, FlowConfig } from '../../src/engine/types.ts';
import { accrualLayout, aggregation, col, costItem, f, form02AdjustColumns, keyColumns, PAY_DESCRIPTION, paymentLayout, signDateNextMonth, signerParams, unitDeduction } from '../common.ts';

const SAL = 'SalaryTable';
const x = (field: string) => `in.${SAL}.${field}`;
const e = (id: string, label: string, formula: string, show = false): EmployeeColumn => ({ id, label, formula, type: 'number', show });

// Payroll columns read 1:1 from the export (Form 01 XLOOKUP by Mã NV)
const READ: [string, string][] = [
  ['alloc1_raw', 'Lương phân bổ (1)'],
  ['concurrent_raw', 'Lương kiêm nhiệm'],
  ['responsibility', 'Phụ cấp T.Nhiệm'],
  ['female', 'Hỗ trợ P.Nữ'],
  ['extra_pay', 'Lương BS thêm'],
  ['leave_tg', 'T.Phép Lg.TG'],
  ['away', 'Hỗ trợ Chi phí Xa nhà'],
  ['wear', 'HT Chi phí Hao mòn'],
  ['meal', 'HT Chi phí Ăn'],
  ['phone', 'HT Điện thoại'],
  ['travel', 'HT Đi Lại'],
  ['house', 'HT Nhà'],
  ['house_wh3', 'HT Nhà WH3'],
  ['work_support', 'HT công việc'],
  ['house_slmk', 'HTThuê Nhà SL&MK'],
  ['away_slmk', 'HT Xa Nhà SL&MK.'],
  ['travel_slmk', 'HT Đi lại SL&MK.'],
  ['toxic', 'Lương độc hại'],
  ['back_pay', 'Truy Lãnh'],
  ['business_trip', 'Lương công tác'],
  ['study', 'Lương học'],
  ['support2', 'Lương phân bổ 2 (hỗ trợ)'],
  ['ins_comp', 'Bù Bảo hiểm'],
  ['total_income', 'Tổng thu nhập'],
  ['si', 'BHXH'],
  ['hi', 'BH Y tế'],
  ['ui', 'BH thất nghiệp'],
  ['pit', 'Thuế TNCN'],
  ['ot', 'LgThêm giờ (k thuế)'],
  ['night', 'Phụcấp Ca3 (k thuế)'],
  ['leave_nv', 'Lương Phép NV (k thuế)'],
  ['donation', 'Ủng hộ'],
  ['unit_keep', 'Đơn vị giữ lại'],
  ['youth_fee', 'Đ.phí TNiên'],
  ['union_fee', 'Đ.phí cđòan'],
  ['party_fee', 'Đảng phí'],
  ['pit_add', 'BS thuế thu nhập'],
  ['welfare_loan', 'Vay PL'],
  ['union_loan', 'Vay CĐ'],
  ['other2', 'Thu khác 2'],
  ['unit_fund', 'Quỹ đơn vị'],
  ['net', 'Thực lãnh'],
];

const cost = (id: string, parts: string[]): EmployeeColumn => e(id, id.replace(/^c/, ''), `ROUND(${parts.map((p) => `[${p}]`).join(' + ')}, 0)`, true);

export const HQ: FlowConfig = {
  schemaVersion: 1,
  id: 'HQ',
  name: 'HQ — Trích & chi lương khối văn phòng / sản xuất',
  ledger: 'shared',
  fileName: 'Form_HQ_{group}_T{MM}.{YYYY}.xlsx',
  inputs: [
    {
      id: SAL,
      label: 'Bảng lương (Salary Table)',
      required: true,
      key: 'emp_id',
      fields: [
        f('emp_id', 'Mã NV', 'text', true),
        f('dv', 'Mã ĐV', 'text'),
        f('unit', 'Mã BP', 'text', true),
        f('name', 'Họ và tên', 'text'),
        ...READ.map(([id, h]) => f(id, h)),
      ],
    },
  ],
  runParams: [{ id: 'group', label: 'Đơn vị (dòng "Đơn vị:" trên Form, ví dụ TPT / PP1)', type: 'text', required: true }, ...signerParams(true)],
  employeeTable: {
    source: SAL,
    rowFilter: null,
    columns: [
      { id: 'emp_id', label: 'Mã NV', formula: x('emp_id'), type: 'text' },
      { id: 'dv', label: 'Mã ĐV', formula: x('dv'), type: 'text' },
      { id: 'unit', label: 'Mã BP', formula: x('unit'), type: 'text' },
      { id: 'name', label: 'Họ và tên', formula: x('name'), type: 'text' },
      // SalaryTable[Group] = XLOOKUP(Mã BP, D_Position[Unit Code], D_Position[Group], "In-direct Production")
      { id: 'group', label: 'Group', formula: 'LOOKUP("UnitGroup", [unit], "Group", "In-direct Production")', type: 'text' },
      ...READ.map(([id, h]) => e(id, h, x(id))),
      e('alloc1', 'Lương phân bổ (1)', `IF([group] = "In-direct Production", [alloc1_raw], 0)`),
      e('concurrent', 'Lương kiêm nhiệm', `IF([group] = "In-direct Production", [concurrent_raw], 0)`),
      e('product', 'Lương sản phẩm', `IF([group] = "Direct Production", [alloc1_raw], 0)`),
      cost('c0301', ['product']),
      cost('c0303', ['leave_tg', 'leave_nv']),
      cost('c0304', ['alloc1', 'back_pay', 'concurrent']),
      cost('c0305', ['support2']),
      cost('c0306', ['business_trip', 'study']),
      cost('c0307', ['extra_pay']),
      cost('c0321', ['night']),
      cost('c0309', ['ot']),
      cost('c0316', ['ins_comp']),
      cost('c0407M_RE', ['responsibility', 'work_support']),
      cost('c0407M_HS', ['house', 'house_wh3', 'house_slmk']),
      cost('c0404', ['away', 'away_slmk']),
      cost('c0406', ['wear']),
      cost('c0401', ['meal']),
      cost('c0416', ['travel', 'travel_slmk']),
      cost('c0417', ['phone']),
      cost('c0420', ['toxic']),
    ],
  },
  costItems: [
    costItem('0304', 'Trích Lương Vị Trí Công Việc', 'HR', 'c0304', true, true),
    costItem('0301', 'Trích Lương Theo Sản Lượng Sản Xuất', 'HR0201', 'c0301', true, true),
    costItem('0307', 'Trích Lương Bổ Sung', 'HR', 'c0307', true, true),
    costItem('0303', 'Trích Lương Thời Gian', 'HR', 'c0303', true, true),
    costItem('0306', 'Trích Lương Học, Phong Trào', 'HR', 'c0306', true, true),
    costItem('0316', 'Trích Bù Bảo Hiểm', 'HR', 'c0316', true, true),
    costItem('0321', 'Trích Phụ Cấp Ca Đêm', 'HR', 'c0321', true, true),
    costItem('0407M_RE', 'Trích Phụ Cấp Trách Nhiệm', 'HR1000', 'c0407M_RE', true, true),
    costItem('0309', 'Trích Lương Thêm Giờ', 'HR', 'c0309', true, true),
    costItem('0404', 'Trích Phụ Cấp Xa Nhà', 'HR1000', 'c0404', true, true),
    costItem('0406', 'Trích Phụ Cấp Hao Mòn', 'HR1000', 'c0406', true, true),
    // Meal allowance is accrued but paid inside the salary rows (Form 03 "Meal Allowance" column)
    costItem('0401', 'Trích Phụ Cấp Tiền Ăn', 'AT', 'c0401', true, false),
    costItem('0417', 'Trích Phụ Cấp Điện Thoại', 'HR1000', 'c0417', true, true),
    costItem('0416', 'Trích Tiền Hỗ Trợ Đi Lại', 'HR1000', 'c0416', true, true),
    costItem('0305', 'Trích Lương Hỗ Trợ, Ngừng Việc', 'HR0201', 'c0305', true, true),
    costItem('0420', 'Trích Phụ Cấp Nặng Nhọc Độc Hại', 'HR1000', 'c0420', true, true),
    costItem('0407M_HS', 'Trích Hỗ Trợ Tiền Nhà', 'HR1000', 'c0407M_HS', true, true),
  ],
  // Definition 01 keeps SB/WH <> "SB"; Unit drops codes containing "Z"
  aggregation: aggregation('AND(CC("SB/WH") <> "SB", NOT(CONTAINS(row.unit, "Z")))'),
  forms: {
    form02: {
      enabled: true,
      prefix: '',
      // Form02 query: drop meal allowance of warehouse departments
      rowFilter: 'NOT(AND(LEFT(row.dept, 2) = "WH", row.costCode = "0401"))',
      adjust: true,
      ledgerFeed: { sheet: 'accrual', amountColumn: 'accrual' },
      columns: form02AdjustColumns(),
      layout: accrualLayout(
        'Form 02 - Print',
        'BẢNG TỔNG HỢP TRÍCH LƯƠNG - THÁNG {MM}.{YYYY}',
        'SUMMARY TABLE OF SALARY ACCRUAL - {MM}.{YYYY}',
        signDateNextMonth('{=IF(run.group = "PP1", "01", "02")}'),
        { preLines: ['Đơn vị: {group}'] },
      ),
    },
    form03: {
      enabled: true,
      prefix: '',
      rowFilter: null,
      adjust: false,
      ledgerFeed: { sheet: 'actual', amountColumn: 'fund' },
      columns: [
        ...keyColumns(PAY_DESCRIPTION),
        col('fund', 'Quỹ lương thực chi', 'Salary fund (actual spending)', 'row.amount', 'number', 19),
        col('meal', 'Tiền ăn', 'Meal Allowance', unitDeduction('meal', ['0304', '0301']), 'number', 12.8),
        col('female', 'PC Phụ Nữ', 'Female-specific allowance', unitDeduction('female', ['0304', '0301']), 'number', 14.3),
        col('si', 'BHXH', 'SI', unitDeduction('si', ['0304', '0301']), 'number', 14),
        col('hi', 'BHYT', 'HI', unitDeduction('hi', ['0304', '0301']), 'number', 13),
        col('ui', 'BHTN', 'UI', unitDeduction('ui', ['0304', '0301']), 'number', 12.8),
        col('pit', 'Thuế TNCN', 'PIT', unitDeduction('pit', ['0304', '0301']), 'number', 13.7),
        col('fund3', 'Đơn vị giữ lại', '3% fund', unitDeduction('unit_keep', ['0307']), 'number', 11.9),
        col('youth', 'Đ.phí TNiên', 'Youth union fee', unitDeduction('youth_fee', ['0304', '0301']), 'number', 10.8),
        col('union', 'Đ.phí cđòan', 'Trade union fee', unitDeduction('union_fee', ['0304', '0301']), 'number', 15.1),
        col('party', 'Đảng phí', 'Party fee', unitDeduction('party_fee', ['0304', '0301']), 'number', 11.9),
        col('unitfund', 'Quỹ trừ tại đơn vị', 'Unit fund', unitDeduction('unit_fund', ['0304', '0301']), 'number', 11),
        col('unionloan', 'Vay CD', 'Trade union loan', unitDeduction('union_loan', ['0304', '0301']), 'number', 11),
        col('welfareloan', 'Vay phúc lợi', 'Welfare fund loan', unitDeduction('welfare_loan', ['0304', '0301']), 'number', 11),
        col('backtax', 'Hoàn thuế', 'Back taxes', '0', 'number', 11, { hideIfZeroTotal: true }),
        col('pitadd', 'Truy thu thuế', 'PIT adding', unitDeduction('pit_add', ['0304', '0301']), 'number', 17.2),
        col('donation', 'Quỹ tấm lòng vàng', 'Donation', unitDeduction('donation', ['0304', '0301']), 'number', 14.3),
        col('other', 'Thu khác', 'Other receivables', unitDeduction('other2', ['0304', '0301']), 'number', 12),
        col(
          'net',
          'Thực lãnh',
          'Take-home pay',
          '[fund] + [meal] + [female] - ([si] + [hi] + [ui] + [pit] + [fund3] + [youth] + [union] + [party] + [unitfund] + [unionloan] + [welfareloan] + [backtax] + [pitadd] + [donation] + [other])',
          'number',
          16.9,
        ),
      ],
      layout: paymentLayout(
        'Form 03 - Print',
        'BẢNG TỔNG HỢP CHI LƯƠNG - THÁNG {MM}.{YYYY}',
        'SUMMARY TABLE OF SALARY PAYMENT - {MM}.{YYYY}',
        signDateNextMonth('03'),
        { preLines: ['Đơn vị: {group}'] },
      ),
    },
  },
  checks: [
    { id: 'dup_emp', level: 'error', scope: 'employee', formula: 'COUNTIFS(in.SalaryTable.emp_id, [emp_id]) = 1', message: 'Mã NV xuất hiện nhiều lần trong Salary Table' },
    { id: 'blank_unit', level: 'error', scope: 'employee', formula: 'NOT(ISBLANK([unit]))', message: 'Nhân viên không có Mã BP' },
    {
      id: 'alloc_split',
      level: 'error',
      scope: 'employee',
      formula: '[alloc1] + [product] = [alloc1_raw]',
      message: 'Lương phân bổ (1) chưa chia hết sang Lương phân bổ / Lương sản phẩm (Form 01 Check Lương phân bổ)',
    },
    {
      id: 'form02_total',
      level: 'error',
      scope: 'total',
      formula:
        'SUM(f02.accrual) = SUM(emp.c0301, emp.c0303, emp.c0304, emp.c0305, emp.c0306, emp.c0307, emp.c0321, emp.c0309, emp.c0316, emp.c0407M_RE, emp.c0407M_HS, emp.c0404, emp.c0406, emp.c0401, emp.c0416, emp.c0417, emp.c0420) - SUMIFS(emp.c0401, emp.dv, "WH*")',
      message: 'Tổng Form 02 ≠ tổng các khoản của bảng nhân viên trừ tiền ăn kho (Form 02!J1)',
    },
    {
      id: 'form03_total',
      level: 'error',
      scope: 'total',
      formula:
        'SUM(f03.fund) + SUM(f03.meal) = SUM(emp.c0301, emp.c0303, emp.c0304, emp.c0305, emp.c0306, emp.c0307, emp.c0321, emp.c0309, emp.c0316, emp.c0407M_RE, emp.c0407M_HS, emp.c0404, emp.c0406, emp.c0401, emp.c0416, emp.c0417, emp.c0420)',
      message: 'Quỹ lương thực chi + tiền ăn trên Form 03 ≠ tổng các khoản của bảng nhân viên (Form 03!J1)',
    },
    { id: 'meal_total', level: 'error', scope: 'total', formula: 'SUM(f03.meal) = SUM(emp.c0401)', message: 'Tiền ăn trên Form 03 ≠ tổng 0401 (Form 03!K1)' },
    { id: 'female_total', level: 'error', scope: 'total', formula: 'SUM(f03.female) = SUM(emp.female)', message: 'PC Phụ Nữ trên Form 03 ≠ tổng Hỗ trợ P.Nữ (Form 03!L1)' },
    { id: 'net_positive', level: 'error', scope: 'form03', formula: '[net] >= 0', message: 'Thực lãnh âm (Form 03!AA1)' },
    { id: 'net_total', level: 'error', scope: 'total', formula: 'SUM(f03.net) = SUM(in.SalaryTable.net)', message: 'Tổng Thực lãnh Form 03 ≠ tổng Thực lãnh của Salary Table (Form 03!AB1)' },
    {
      id: 'pit_double',
      level: 'warning',
      scope: 'form03',
      formula: 'UNITCOUNT([pit] <> 0) <= 1',
      message: 'Đơn vị có hơn một dòng nhận TNCN (có cả 0301 và 0304) — kiểm tra phân bổ',
    },
  ],
  extraSheets: [],
};

// D14: deduction columns whose total is zero are hidden on the printed Form 03
for (const c of HQ.forms.form03.columns) if (c.type === 'number' && !['no', 'fund', 'net'].includes(c.id)) c.hideIfZeroTotal = true;
