// 002 SL — Salary accrual / payment of the sales network (SB units).
import type { EmployeeColumn, FlowConfig } from '../../src/engine/types.ts';
import { accrualLayout, aggregation, col, costItem, f, form02AdjustColumns, keyColumns, PAY_DESCRIPTION, paymentLayout, signDateNextMonth, signerParams, unitDeduction } from '../common.ts';

const n = (id: string, label: string, formula: string, show = false): EmployeeColumn => ({ id, label, formula, type: 'number', show });
/** ROUND(SUMIFS(SalaryTable[x], SalaryTable[Mã NV], Mã NV), 0) */
const sumST = (field: string) => `ROUND(SUMOF(in.SalaryTable.${field}), 0)`;
/** ROUND(SUMIFS(SalaryDetail[Lương], SalaryDetail[Mã NV], Mã NV, SalaryDetail[Loại Lương], type, …), 0) */
const detail = (type: string, extra = '') => `ROUND(SUMIFS(in.SalaryDetail.amount, in.SalaryDetail.salary_type, "${type}"${extra}), 0)`;
const MR = '"Medical Representative"';

// Salary Table columns (header text of the payroll export)
const ST: [string, string][] = [
  ['time_salary', 'Lương thời gian'],
  ['alloc', 'Lương phân bổ'],
  ['concurrent', 'Lương kiêm nhiệm'],
  ['target_tender', 'Thưởng đạt khoán +Thầu'],
  ['kpi_compliance', 'Thưởng tuân thủ/KPI'],
  ['bonus_qy', 'Thưởng (Quý/N)'],
  ['away', 'Hỗ trợ Chi phí Xa nhà'],
  ['wear', 'HT Chi phí Hao mòn'],
  ['meal', 'HT Chi phí Ăn'],
  ['phone', 'HT Điện thoại'],
  ['travel', 'HT Đi Lại'],
  ['house', 'HT Nhà'],
  ['house_wh3', 'HT Nhà WH3'],
  ['work_support', 'HT công việc'],
  ['company_support', 'Công ty Hỗ trợ/Truy lãnh'],
  ['ins_comp', 'Bù Bảo hiểm'],
  ['female', 'Hỗ trợ Phụ Nữ'],
  ['extra_pay', 'Lương thêm'],
  ['regional', 'Lương hỗ trợ TT Vùng'],
  ['support70', 'Lương hỗ trợ (70%)'],
  ['total_income', 'Tổng thu nhập'],
  ['si', 'BHXH'],
  ['hi', 'Bảo hiểm Y tế'],
  ['ui', 'Bảo hiểm thất nghiệp'],
  ['ins_total', 'Tổng Bảo hiểm'],
  ['family_deduction', 'Giảm trừ Gia cảnh'],
  ['pit', 'Thuế TNCN (L1)'],
  ['ot', 'Lương thêm giờ (k thuế)'],
  ['leave_quit', 'Lương Phép Nghỉ Việc (k thuế)'],
  ['donation', 'Tthiện, T.Trợ,B.Trợ , Ủng hộ'],
  ['unit_keep', 'Quỹ đơn vị giữ lại'],
  ['youth_fee', 'Đoàn phí Th.Niên'],
  ['union_fee', 'Đoàn phí công đòan'],
  ['party_fee', 'Đảng phí'],
  ['fund24', 'Quỹ (2-4%)'],
  ['meal_receivable', 'Thu tiền ăn tại đv'],
  ['unit_fund', 'Quỹ trừ tại đơn vị'],
  ['union_loan', 'Vay CD'],
  ['welfare_loan', 'Vay phúc lợi'],
  ['advance_return', 'Hoàn ứng'],
  ['other', 'Du lịch, Thu Khác'],
  ['back_tax', 'Truy thu thuế'],
  ['tds', 'Thưởng doanh số (TDS)'],
  ['pit_tds', 'Thuế thu nhập (TDS)'],
  ['cash_collect', 'Lương thu tiền'],
];

/** Units whose salary goes to 0304 (workbook: Mã BP = WH1D, TR or ending with a digit) — CostCenter flag. */
const IS_0304 = 'CC("Lương 0304")';

export const SL: FlowConfig = {
  schemaVersion: 1,
  id: 'SL',
  name: 'SL — Trích & chi lương khối bán hàng',
  ledger: 'shared',
  fileName: 'Form_SL_T{MM}.{YYYY}.xlsx',
  inputs: [
    {
      id: 'SalaryTable',
      label: 'Bảng lương (Salary Table)',
      required: true,
      key: 'emp_id',
      fields: [
        f('emp_id', 'Mã NV', 'text', true),
        f('dv', 'Mã ĐV', 'text'),
        f('unit', 'Mã BP', 'text', true),
        f('name', 'Họ và tên', 'text'),
        f('sales', 'Doanh số thực tế'),
        ...ST.map(([id, h]) => f(id, h)),
      ],
    },
    {
      id: 'SalaryDetail',
      label: 'Chi tiết lương (Salary Detail)',
      required: true,
      key: 'emp_id',
      fields: [
        f('period_type', 'Loại Kỳ', 'text'),
        f('emp_id', 'Mã NV', 'text', true),
        f('title', 'Chức Danh', 'text'),
        f('amount', 'Lương', 'number', true),
        f('salary_type', 'Loại Lương', 'text', true),
      ],
      computed: [
        // SalaryDetail[Tính thưởng] = XLOOKUP(Chức Danh, D_Position[Tên chức danh], D_Position[Tính thưởng], "")
        { id: 'bonus_group', label: 'Tính thưởng', formula: 'LOOKUP("SalesPosition", in.SalaryDetail.title, "Tính thưởng", "")', type: 'text' },
        // SalaryDetail[Tính lương] = IF(AND(Tính thưởng = "Sales Representative", Doanh số > 0), "Sales Representative", "Others")
        {
          id: 'salary_group',
          label: 'Tính lương',
          formula: 'IF(AND(in.SalaryDetail.bonus_group = "Sales Representative", in.SalaryTable.sales > 0), "Sales Representative", "Others")',
          type: 'text',
        },
      ],
    },
  ],
  runParams: signerParams(true),
  employeeTable: {
    source: 'SalaryTable',
    rowFilter: null,
    columns: [
      { id: 'emp_id', label: 'Mã NV', formula: 'in.SalaryTable.emp_id', type: 'text' },
      { id: 'dv', label: 'Mã ĐV', formula: 'in.SalaryTable.dv', type: 'text' },
      { id: 'unit', label: 'Mã BP', formula: 'in.SalaryTable.unit', type: 'text' },
      { id: 'name', label: 'Họ và tên', formula: 'TRIM(in.SalaryTable.name)', type: 'text' },
      n('time_salary', 'Lương thời gian', 'SUMOF(in.SalaryTable.time_salary)'),
      n('ds_salary', 'Lương doanh số', detail('Lương Tháng x Hệ số (+)', ', in.SalaryDetail.salary_group, "Sales Representative"')),
      n('ds_return_q', 'Lương doanh số hoàn lại (Quý)', detail('Thưởng lương sản phẩm (+)', ', in.SalaryDetail.salary_group, "Sales Representative"')),
      n('big_customer', 'Lương khách hàng lớn', detail('Lương Khách Hàng Lớn (+)')),
      n('big_customer_unit', 'Lương khách hàng lớn Chi lại đơn vị', detail('*Đơn Vị (+)')),
      n('cash_month', 'Lương thu tiền tháng', detail('Lương Thu Tiền (NVBH thu) (+)')),
      n('allowance', 'Phụ cấp', detail('Lương Phụ Cấp (+)')),
      n('alloc', 'Lương phân bổ', 'ROUND(SUMOF(in.SalaryTable.alloc) - [ds_salary] - [big_customer] - [big_customer_unit] - [allowance] - [ds_return_q], 0)'),
      n('concurrent', 'Lương kiêm nhiệm', sumST('concurrent')),
      n('tender', 'Lương hàng thầu', `${detail('Lương Thầu Kênh Hospital (+)')} + ${detail('Lương Thầu Kênh Hospital Quý (+)')}`),
      n('target_month', 'Thưởng đạt khoán tháng', detail('Thưởng Đạt Khoán (+)', `, in.SalaryDetail.bonus_group, "<>" & ${MR}`)),
      n('incentive_month', 'Thưởng Khích lệ bán hàng tháng', detail('Thưởng Đạt Khoán (+)', `, in.SalaryDetail.bonus_group, ${MR}`)),
      n(
        'target_quarter',
        'Thưởng đạt khoán quý',
        `ROUND(SUMIFS(in.SalaryDetail.amount, in.SalaryDetail.salary_type, "Thưởng Đạt Khoán Quý (+)", in.SalaryDetail.bonus_group, "<>" & ${MR}) + SUMIFS(in.SalaryDetail.amount, in.SalaryDetail.salary_type, "Thưởng KPI*", in.SalaryDetail.period_type, "Quý", in.SalaryDetail.bonus_group, "<>" & ${MR}), 0)`,
      ),
      n(
        'incentive_quarter',
        'Thưởng Khích lệ bán hàng quý',
        `ROUND(SUMIFS(in.SalaryDetail.amount, in.SalaryDetail.salary_type, "Thưởng Đạt Khoán Quý (+)", in.SalaryDetail.bonus_group, ${MR}) + SUMIFS(in.SalaryDetail.amount, in.SalaryDetail.salary_type, "Thưởng KPI*", in.SalaryDetail.bonus_group, ${MR}), 0)`,
      ),
      n('excess_quarter', 'Thưởng vượt khoán quý', detail('Thưởng Vượt Khoán (+)')),
      n('cash_quarter', 'Thưởng thu tiền (Quý/N)', detail('Thưởng NVBH Thu Tiền Quý (+)')),
      n('group_sales', 'Thưởng nhóm sp (thưởng P)', detail('Thưởng doanh số nhóm thầu/áp thầu & ngoài thầu (+)')),
      n('kpi_year', 'Thưởng KPI năm', detail('Thưởng KPI năm (+)')),
      n('target_year', 'Thưởng đạt khoán năm', detail('Thưởng DS năm (+)')),
      n('away', 'Hỗ trợ Chi phí Xa nhà', sumST('away')),
      n('wear', 'HT Chi phí Hao mòn', sumST('wear')),
      n('meal', 'HT Chi phí Ăn', sumST('meal')),
      n('phone', 'HT Điện thoại', sumST('phone')),
      n('travel', 'HT Đi Lại', sumST('travel')),
      n('house', 'HT Nhà', sumST('house')),
      n('house_wh3', 'HT Nhà WH3', sumST('house_wh3')),
      n('work_support', 'HT công việc', sumST('work_support')),
      n('female', 'Hỗ trợ Phụ Nữ', sumST('female')),
      // Form 01 uses SUMIFS(tbl_additionalsalary[Additional Salary], …) = "x"; SUMIFS of a text flag is always 0 in Excel,
      // so the intent (listed employees only) is written as a lookup — see docs/phase5-mapping.md
      n(
        'company_support',
        'Công ty Hỗ trợ/Truy lãnh',
        'IF(LOOKUP("AdditionalSalary", [emp_id], "Additional Salary", "") = "x", ROUND(SUMOF(in.SalaryTable.company_support) - [female], 0), 0)',
      ),
      n('mtc', 'Lương MTC', '0'),
      n('ins_comp', 'Bù Bảo hiểm', sumST('ins_comp')),
      n('extra_pay', 'Lương thêm', sumST('extra_pay')),
      n('regional', 'Lương hỗ trợ TT Vùng', sumST('regional')),
      n('support70', 'Lương hỗ trợ (70%)', sumST('support70')),
      n('si', 'BHXH', sumST('si')),
      n('hi', 'Bảo hiểm Y tế', sumST('hi')),
      n('ui', 'Bảo hiểm thất nghiệp', sumST('ui')),
      n('family_deduction', 'Giảm trừ Gia cảnh', sumST('family_deduction')),
      n('pit', 'Thuế TNCN (L1)', sumST('pit')),
      n('ot', 'Lương thêm giờ (k thuế)', sumST('ot')),
      n('leave_quit', 'Lương Phép Nghỉ Việc (k thuế)', sumST('leave_quit')),
      n('donation', 'Tthiện, T.Trợ,B.Trợ , Ủng hộ', sumST('donation')),
      n('unit_keep', 'Quỹ đơn vị giữ lại', sumST('unit_keep')),
      n('youth_fee', 'Đoàn phí Th.Niên', sumST('youth_fee')),
      n('union_fee', 'Đoàn phí công đòan', sumST('union_fee')),
      n('party_fee', 'Đảng phí', sumST('party_fee')),
      n('meal_receivable', 'Thu tiền ăn tại đv', sumST('meal_receivable')),
      n('unit_fund', 'Quỹ trừ tại đơn vị', sumST('unit_fund')),
      n('union_loan', 'Vay CD', sumST('union_loan')),
      n('welfare_loan', 'Vay phúc lợi', sumST('welfare_loan')),
      n('other', 'Du lịch, Thu Khác', sumST('other')),
      n('back_tax', 'Truy thu thuế', sumST('back_tax')),
      n('tds', 'Thưởng doanh số (TDS)', sumST('tds')),
      n('pit_tds', 'Thuế thu nhập (TDS)', sumST('pit_tds')),
      n('support_0304', 'Truy lãnh + MT 0304', `IF(${IS_0304}, [company_support] + [mtc], 0)`),
      n('support_0319', 'Truy lãnh + MT 0319', `IF(${IS_0304}, 0, [company_support] + [mtc])`),
      n('alloc_st', 'Lương phân bổ (ST)', 'ROUND(in.SalaryTable.alloc, 0)'),
      n('alloc_0304', 'Lương Phân bổ 0304', `IF(${IS_0304}, [alloc_st], 0)`),
      n('alloc_0319', 'Lương Phân bổ 0319', `IF(${IS_0304}, 0, [alloc_st])`),
      {
        id: 'bonus_group',
        label: 'Nhóm chức danh tính thưởng',
        formula: 'IF(ISBLANK(FIRST(in.SalaryDetail.emp_id)), "Others", FIRST(in.SalaryDetail.bonus_group))',
        type: 'text',
        show: false,
      },
      n('c0303', '0303', 'ROUND([time_salary] + [leave_quit], 0)', true),
      n('c0304', '0304', 'ROUND([alloc_0304] + [support_0304] + [concurrent], 0)', true),
      n('c0305', '0305', 'ROUND([regional] + [support70], 0)', true),
      n('c0307', '0307', 'ROUND([extra_pay], 0)', true),
      n('c0308', '0308', 'ROUND([tds], 0)', true),
      n('c0309', '0309', 'ROUND([ot], 0)', true),
      n('c0316', '0316', 'ROUND([ins_comp], 0)', true),
      n('c0319', '0319', 'ROUND([alloc_0319] + [support_0319], 0)', true),
      n('c0404', '0404', 'ROUND([away], 0)', true),
      n('c0406', '0406', 'ROUND([wear], 0)', true),
      n('c0407M_HS', '0407M_HS', 'ROUND([house] + [house_wh3], 0)', true),
      n('c0407M_RE', '0407M_RE', 'ROUND([allowance] + [work_support], 0)', true),
      n('c0401', '0401', 'ROUND([meal], 0)', true),
      n('c0417', '0417', 'ROUND([phone], 0)', true),
      n('c0416', '0416', 'ROUND([travel], 0)', true),
      n('c0311M', '0311M', '0', false),
      n('c0311Q', '0311Q', '0', false),
      n('c0317M_TB', '0317M_TB', '[tender]', true),
      n('c0317M_ST', '0317M_ST', '[target_month]', true),
      n('c0323M', '0323M', '[cash_month]', true),
      n('c0317M_SI', '0317M_SI', '[incentive_month]', true),
      n('c0317Q_ST', '0317Q_ST', '[target_quarter]', true),
      n('c0323Q', '0323Q', '[cash_quarter]', true),
      n('c0317Q_GS', '0317Q_GS', '[group_sales]', true),
      n('c0317Q_SI', '0317Q_SI', '[incentive_quarter]', true),
      n('c0322Q', '0322Q', '[excess_quarter]', true),
      n('c0317Y_ST', '0317Y_ST', '[kpi_year] + [target_year]', true),
    ],
  },
  costItems: [
    // monthly items are accrued here; quarterly / yearly ones are accrued by QHY and only paid here
    costItem('0303', 'Trích Lương Thời Gian', 'HR', 'c0303', true, true),
    costItem('0304', 'Trích Lương Vị Trí Công Việc', 'HR', 'c0304', true, true),
    costItem('0305', 'Trích Lương Hỗ Trợ, Ngừng Việc', 'HR', 'c0305', true, true),
    costItem('0307', 'Trích Lương Bổ Sung', 'HR', 'c0307', true, true),
    costItem('0308', 'Trích Thưởng Doanh Số', 'HR', 'c0308', true, true),
    costItem('0309', 'Trích Lương Thêm Giờ', 'HR', 'c0309', true, true),
    costItem('0311M', 'Trích Thưởng KPI Tháng', 'HR', 'c0311M', true, true),
    costItem('0311Q', 'Trích Thưởng KPI Quý', 'HR', 'c0311Q', false, true),
    costItem('0316', 'Trích Bù Bảo Hiểm', 'HR', 'c0316', true, true),
    costItem('0323M', 'Trích Thưởng Thu Tiền Tháng', 'HR', 'c0323M', true, true),
    costItem('0317M_ST', 'Trích Thưởng Doanh Số Tháng', 'HR', 'c0317M_ST', true, true),
    costItem('0317M_TB', 'Trích Lương Thầu', 'HR', 'c0317M_TB', true, true),
    costItem('0323Q', 'Trích Thưởng Thu Tiền Quý', 'HR', 'c0323Q', false, true),
    costItem('0317Q_GS', 'Trích Thưởng Doanh Số Nhóm Hàng Quý', 'HR', 'c0317Q_GS', false, true),
    costItem('0317Q_ST', 'Trích Thưởng Doanh Số Quý', 'HR', 'c0317Q_ST', false, true),
    costItem('0319', 'Trích Lương Theo Doanh Số Nhóm Hàng', 'HR', 'c0319', true, true),
    costItem('0404', 'Trích Phụ Cấp Xa Nhà', 'HR1000', 'c0404', true, true),
    costItem('0406', 'Trích Phụ Cấp Hao Mòn', 'HR1000', 'c0406', true, true),
    // sl_form02.m drops Helper "0401": meal allowance only appears as the Form 03 "Meal Allowance" column
    costItem('0401', 'Trích Phụ Cấp Tiền Ăn', 'AT', 'c0401', false, false),
    costItem('0417', 'Trích Phụ Cấp Điện Thoại', 'HR1000', 'c0417', true, true),
    costItem('0317M_SI', 'Trích Thưởng Khích Lệ Bán Hàng Tháng', 'HR', 'c0317M_SI', true, true),
    costItem('0317Q_SI', 'Trích Thưởng Khích Lệ Bán Hàng Quý', 'HR', 'c0317Q_SI', false, true),
    costItem('0322Q', 'Trích Thưởng Vượt Quý', 'HR', 'c0322Q', false, true),
    costItem('0317Y_ST', 'Trích Thưởng Doanh Số Năm', 'HR', 'c0317Y_ST', false, true),
    costItem('0416', 'Trích Tiền Hỗ Trợ Đi Lại', 'HR1000', 'c0416', true, true),
    costItem('0407M_HS', 'Trích Hỗ Trợ Tiền Nhà', 'HR1000', 'c0407M_HS', true, true),
    costItem('0407M_RE', 'Trích Phụ cấp Trách Nhiệm', 'HR1000', 'c0407M_RE', true, true),
  ],
  // Definition 01 keeps SB/WH = "SB"; Unit drops codes containing "Z"
  aggregation: aggregation('AND(CC("SB/WH") = "SB", NOT(CONTAINS(row.unit, "Z")))'),
  forms: {
    form02: {
      enabled: true,
      prefix: '',
      rowFilter: null,
      adjust: true,
      ledgerFeed: { sheet: 'accrual', amountColumn: 'accrual' },
      columns: form02AdjustColumns(),
      layout: accrualLayout(
        'Form 02 - Print',
        'BẢNG TỔNG HỢP TRÍCH LƯƠNG KHỐI BÁN HÀNG - THÁNG {MM}.{YYYY}',
        'SUMMARY TABLE OF SALARY ACCRUAL (SALES) - {MM}.{YYYY}',
        signDateNextMonth('03'),
      ),
    },
    form03: {
      enabled: true,
      prefix: '',
      rowFilter: null,
      adjust: false,
      ledgerFeed: { sheet: 'actual', amountColumn: 'fund' },
      columns: [
        ...keyColumns(PAY_DESCRIPTION),
        col('fund', 'Quỹ lương thực chi', 'Salary fund (actual spending)', 'row.amount', 'number', 14.4),
        col('meal', 'Tiền ăn', 'Meal Allowance', unitDeduction('meal', ['0304', '0319']), 'number', 12),
        col('female', 'PC Phụ Nữ', 'Female-specific allowance', unitDeduction('female', ['0304', '0319']), 'number', 11.9),
        col('si', 'BHXH', 'SI', unitDeduction('si', ['0304', '0319']), 'number', 13),
        col('hi', 'BHYT', 'HI', unitDeduction('hi', ['0304', '0319']), 'number', 12),
        col('ui', 'BHTN', 'UI', unitDeduction('ui', ['0304', '0319']), 'number', 12),
        // Check Allocation PIT: HC-numbered cost centres put PIT on 0317Q_SI when that row exists, else on 0304 / 0319
        col(
          'pit_x',
          'Check Allocation PIT',
          'Check Allocation PIT',
          'IF(ISNUMBER(VALUE(SUBSTITUTE(row.costCenter, "HC", ""))), IF(GROUPCOUNT(row.costCenter, row.helper = "0317Q_SI") > 0, IF(row.helper = "0317Q_SI", "X", ""), IF(row.costCode IN ("0304", "0319"), "X", "")), IF(row.costCode IN ("0304", "0319"), "X", ""))',
          'text',
          8,
          { hidden: true },
        ),
        col('pit', 'Thuế TNCN', 'PIT', 'ROUND(IFS([pit_x] = "X", UNITSUM(emp.pit), row.costCode = "0308", UNITSUM(emp.pit_tds), TRUE, 0), 0)', 'number', 12),
        col('fund3', 'Đơn vị giữ lại', '3% fund', unitDeduction('unit_keep', ['0307']), 'number', 11),
        col('youth', 'Đ.phí TNiên', 'Youth union fee', unitDeduction('youth_fee', ['0304', '0319']), 'number', 11),
        col('union', 'Đ.phí cđòan', 'Trade union fee', unitDeduction('union_fee', ['0304', '0319']), 'number', 11),
        col('party', 'Đảng phí', 'Party fee', unitDeduction('party_fee', ['0304', '0319']), 'number', 11),
        col('meal_back', 'Tiền ăn thu lại', 'Receivable meal cost', unitDeduction('meal_receivable', ['0304', '0319']), 'number', 11),
        col('unitfund', 'Quỹ trừ tại đơn vị', 'Unit fund', unitDeduction('unit_fund', ['0304', '0319']), 'number', 11),
        col('unionloan', 'Vay CD', 'Trade union loan', unitDeduction('union_loan', ['0304', '0319']), 'number', 11),
        col('welfareloan', 'Vay phúc lợi', 'Welfare fund loan', unitDeduction('welfare_loan', ['0304', '0319']), 'number', 11),
        col('backtax', 'Truy thu thuế', 'Back taxes', unitDeduction('back_tax', ['0304', '0319']), 'number', 14.4),
        col('donation', 'Quỹ tấm lòng vàng', 'Donation', unitDeduction('donation', ['0304', '0319']), 'number', 11),
        col('other', 'Thu khác', 'Other receivables', unitDeduction('other', ['0304', '0319']), 'number', 11),
        col(
          'net',
          'Thực lãnh',
          'Take-home pay',
          '[fund] + [meal] + [female] - ([si] + [hi] + [ui] + [pit] + [fund3] + [youth] + [union] + [party] + [meal_back] + [unitfund] + [unionloan] + [welfareloan] + [backtax] + [donation] + [other])',
          'number',
          13.2,
        ),
      ],
      layout: paymentLayout(
        'Form 03 - Print',
        'BẢNG TỔNG HỢP CHI LƯƠNG KHỐI BÁN HÀNG - THÁNG {MM}.{YYYY}',
        'SUMMARY TABLE OF SALARY PAYMENT (SALES) - {MM}.{YYYY}',
        signDateNextMonth('12'),
      ),
    },
  },
  checks: [
    { id: 'dup_emp', level: 'error', scope: 'employee', formula: 'COUNTIFS(in.SalaryTable.emp_id, [emp_id]) = 1', message: 'Mã NV xuất hiện nhiều lần trong Salary Table' },
    { id: 'blank_unit', level: 'error', scope: 'employee', formula: 'NOT(ISBLANK([unit]))', message: 'Nhân viên không có Mã BP' },
    { id: 'family_deduction', level: 'error', scope: 'employee', formula: '[family_deduction] >= 0', message: 'Giảm trừ gia cảnh âm (Form 01!BL1)' },
    {
      id: 'salary_x_coef',
      level: 'error',
      scope: 'employee',
      formula:
        `NOT(ABS(${detail('Lương tháng x Hệ số (+)')} + ${detail('Lương Tháng (Tối Thiểu Vùng) (+)')} + [big_customer] + [big_customer_unit] + [allowance] + [ds_return_q] - [alloc_st]) >= 100)`,
      message: 'Lương tháng x hệ số + các khoản khác lệch Lương phân bổ ≥ 100 đ (Form 01 Check Lương x HS)',
    },
    {
      id: 'alloc_total',
      level: 'error',
      scope: 'employee',
      formula: '[alloc] + [ds_salary] + [big_customer] + [big_customer_unit] + [allowance] + [ds_return_q] = [alloc_st]',
      message: 'Các phần của Lương phân bổ không cộng lại bằng Lương phân bổ (Form 01 Check tổng lương phân bổ)',
    },
    {
      id: 'big_customer_group',
      level: 'error',
      scope: 'employee',
      formula: 'IF([big_customer] + [big_customer_unit] > 0, [bonus_group] = "Sales Representative", TRUE)',
      message: 'Có lương khách hàng lớn nhưng không thuộc nhóm Sales Representative (Form 01 Check đối tượng hưởng lương KHL)',
    },
    {
      id: 'bonus_total',
      level: 'error',
      scope: 'employee',
      formula:
        'ROUND([tender] + [target_month] + [incentive_month] + [target_quarter] + [incentive_quarter] + [excess_quarter] + [cash_month] + [cash_quarter] + [group_sales] + [kpi_year] + [target_year], 0) = ROUND(in.SalaryTable.target_tender + in.SalaryTable.cash_collect, 0)',
      message: 'Tổng thưởng khoán + thầu + lương thu tiền lệch Salary Table (Form 01 Check Thưởng Khoán + Thầu + Lương thu tiền)',
    },
    {
      id: 'company_support',
      level: 'warning',
      scope: 'employee',
      formula: 'ROUND([company_support] + [mtc], 0) = ROUND(in.SalaryTable.company_support, 0)',
      message: 'Công ty Hỗ trợ/Truy lãnh chưa được đưa đủ vào 0304/0319 (Form 01 Check lương hỗ trợ + MT)',
    },
    {
      id: 'form02_total',
      level: 'error',
      scope: 'total',
      formula:
        'SUM(f02.accrual) = SUM(emp.c0303, emp.c0304, emp.c0305, emp.c0307, emp.c0308, emp.c0309, emp.c0316, emp.c0319, emp.c0404, emp.c0406, emp.c0407M_HS, emp.c0407M_RE, emp.c0417, emp.c0416, emp.c0311M, emp.c0317M_TB, emp.c0317M_ST, emp.c0323M, emp.c0317M_SI)',
      message: 'Tổng Form 02 ≠ tổng các khoản tháng của bảng nhân viên (Form 02!J1, Form 02 - Print!L1)',
    },
    {
      id: 'form03_total',
      level: 'error',
      scope: 'total',
      formula:
        'SUM(f03.fund) = SUM(emp.c0303, emp.c0304, emp.c0305, emp.c0307, emp.c0308, emp.c0309, emp.c0316, emp.c0319, emp.c0404, emp.c0406, emp.c0407M_HS, emp.c0407M_RE, emp.c0417, emp.c0416, emp.c0311M, emp.c0311Q, emp.c0317M_TB, emp.c0317M_ST, emp.c0323M, emp.c0317M_SI, emp.c0317Q_ST, emp.c0323Q, emp.c0317Q_GS, emp.c0317Q_SI, emp.c0322Q, emp.c0317Y_ST)',
      message: 'Quỹ lương thực chi trên Form 03 ≠ tổng các khoản (trừ tiền ăn) của bảng nhân viên (Form 03!J1)',
    },
    { id: 'meal_total', level: 'error', scope: 'total', formula: 'SUM(f03.meal) = SUM(emp.c0401)', message: 'Tiền ăn trên Form 03 ≠ tổng 0401 (Form 03!K1)' },
    { id: 'female_total', level: 'error', scope: 'total', formula: 'SUM(f03.female) = SUM(emp.female)', message: 'PC Phụ Nữ trên Form 03 ≠ tổng Hỗ trợ Phụ Nữ (Form 03!L1)' },
    { id: 'pit_total', level: 'error', scope: 'total', formula: 'SUM(f03.pit) = SUM(emp.pit) + SUM(emp.pit_tds)', message: 'Thuế TNCN đã phân bổ ≠ tổng TNCN (L1 + TDS)' },
    { id: 'pit_double', level: 'warning', scope: 'form03', formula: 'UNITCOUNT([pit_x] = "X") <= 1', message: 'Đơn vị có hơn một dòng nhận TNCN — TNCN bị tính hai lần' },
    { id: 'net_positive', level: 'error', scope: 'form03', formula: '[net] >= 0', message: 'Thực lãnh âm (Form 03!AA1)' },
    {
      id: 'net_total',
      level: 'error',
      scope: 'total',
      formula:
        'SUM(f03.net) = ROUND(SUM(in.SalaryTable.time_salary, in.SalaryTable.alloc, in.SalaryTable.concurrent, in.SalaryTable.target_tender, in.SalaryTable.kpi_compliance, in.SalaryTable.bonus_qy, in.SalaryTable.away, in.SalaryTable.wear, in.SalaryTable.phone, in.SalaryTable.travel, in.SalaryTable.house, in.SalaryTable.house_wh3, in.SalaryTable.work_support, in.SalaryTable.company_support, in.SalaryTable.ins_comp, in.SalaryTable.extra_pay, in.SalaryTable.regional, in.SalaryTable.support70) + SUM(in.SalaryTable.leave_quit) + SUM(in.SalaryTable.ot) + SUM(in.SalaryTable.tds) + SUM(in.SalaryTable.cash_collect), 0) + SUM(in.SalaryTable.female) + SUM(in.SalaryTable.meal) - SUM(in.SalaryTable.ins_total) - SUM(in.SalaryTable.pit) - SUM(in.SalaryTable.pit_tds) - SUM(in.SalaryTable.donation, in.SalaryTable.unit_keep, in.SalaryTable.youth_fee, in.SalaryTable.union_fee, in.SalaryTable.party_fee, in.SalaryTable.fund24, in.SalaryTable.meal_receivable, in.SalaryTable.unit_fund, in.SalaryTable.union_loan, in.SalaryTable.welfare_loan, in.SalaryTable.advance_return, in.SalaryTable.other, in.SalaryTable.back_tax)',
      message: 'Tổng Thực lãnh Form 03 ≠ tổng thực lãnh tính từ Salary Table (Form 03!AB1)',
    },
  ],
  extraSheets: [],
};

for (const c of SL.forms.form03.columns) if (c.type === 'number' && !['no', 'fund', 'net'].includes(c.id)) c.hideIfZeroTotal = true;
